using System;
using System.Text;

namespace CreditCardValidation.SourceGenerator;

public static class SourceGenerationHelper
{
	public static string GetCode(in ClassToGenerate classToGenerate)
	{
		var codeBuilder = new StringBuilder();

		foreach (var property in classToGenerate.Properties)
		{
			codeBuilder.AppendLine($"yield return new PropertyValue(\"{property.ToUpperInvariant()}\", {property});");
		}
		
		var source = $$"""
		               // <auto-generated>
		               // {{DateTime.Now}}"
		               #nullable enable
		               
		               namespace {{classToGenerate.Namespace}};
		               
		               public partial class {{classToGenerate.Name}}
		               {
		                   public override IEnumerable<PropertyValue> GetPropertiesForCreditCardValidation()
		                   {
		                        {{codeBuilder}}
		                   }
		               }
		               """;

		return source;
	}
	
	public static string GetPropertyValueCode()
	{
		var source = $$"""
		               // <auto-generated>
		               // {{DateTime.Now}}"
		               #nullable enable
		               
		               namespace CreditCardValidation;
		               
		               public record PropertyValue(string Property, string? Value);
		               """;

		return source;
	}
}